linters:
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - interfacer
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - scopelint
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/armsnyder/othelgo
  unparam:
    check-exported: true
  unused:
    check-exported: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - unused
