name: Push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run end-to-end tests
        run: make e2etest

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: [ lint, test, build ]
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy
        run: make deploy

  publish-website:
    name: Publish Website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Publish Website
        run: make website
