yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
packageExtensions:
  nollup@*:
    peerDependencies:
      rollup: ^2.0.0
  rollup-plugin-hot-nollup@*:
    peerDependencies:
      rollup: ^2.0.0
